Add scripts formatting.

diff --git a/scripts/start-gdb b/scripts/start-gdb
--- a/scripts/start-gdb
+++ b/scripts/start-gdb
@@ -4,8 +4,8 @@
 BINARY_PATH=${1}
 
 if [ -z ${BINARY_PATH} ]; then
-	echo "No executable provided. Abort."
-	exit 1
+    echo "No executable provided. Abort."
+    exit 1
 fi
 
 cgdb -d arm-none-eabi-gdb -- ${BINARY_PATH} -x tools/scripts/openocd.gdbinit
